package com.sakurac1oud.SenseofCherryBlossom.common.material;

import static com.sakurac1oud.SenseofCherryBlossom.SenseofCherryBlossom.LOG;
import static gregtech.api.enums.Mods.Avaritia;
import static gregtech.api.enums.OrePrefixes.nanite;

import java.util.Arrays;

import com.sakurac1oud.SenseofCherryBlossom.common.render.InfinityStygianRenderer;
import com.sakurac1oud.SenseofCherryBlossom.common.render.InfinityStygianTranscendentMetalRenderer;
import com.sakurac1oud.SenseofCherryBlossom.common.render.StygianRenderer;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.relauncher.Side;
import goodgenerator.util.CharExchanger;
import gregtech.api.enums.*;
import gregtech.common.render.items.*;
import gregtech.common.render.items.*;

public class MaterialCherryBlossom {

    static final int offsetID = 260;
    // ID form 2242 ~ 2298 is available
    public static Materials Stygian = new Materials(
        offsetID + 2,
        TextureSet.SET_METALLIC,
        960.0F,
        1048576000,
        24,
        1 | 2 | 32 | 64 | 128,
        41,
        45,
        27,
        0,
        "Stygian",
        "Stygian",
        -1,
        -1,
        23000,
        26000,
        true,
        false,
        2,
        1,
        1,
        Dyes._NULL,
        Arrays.asList(
            new TCAspects.TC_AspectStack(TCAspects.ORDO, 8),
            new TCAspects.TC_AspectStack(TCAspects.ALIENIS, 20),
            new TCAspects.TC_AspectStack(TCAspects.PERDITIO, 10),
            new TCAspects.TC_AspectStack(TCAspects.METALLUM, 5))).disableAutoGeneratedBlastFurnaceRecipes()
                .disableAutoGeneratedVacuumFreezerRecipe()
                .setProcessingMaterialTierEU(TierEU.RECIPE_UV)
                .setHasCorrespondingPlasma(true);

    public static Materials Demise = new Materials(
        offsetID + 3,
        TextureSet.SET_METALLIC,
        1.0F,
        0,
        2,
        1 | 2 | 32,
        200,
        200,
        200,
        0,
        "Demise",
        "Demise",
        -1,
        -1,
        3231,
        3231213,
        false,
        false,
        2,
        1,
        1,
        Dyes._NULL,
        Arrays.asList(
            new TCAspects.TC_AspectStack(TCAspects.RADIO, 5),
            new TCAspects.TC_AspectStack(TCAspects.METALLUM, 3))).disableAutoGeneratedBlastFurnaceRecipes()
                .disableAutoGeneratedVacuumFreezerRecipe()
                .setProcessingMaterialTierEU(TierEU.RECIPE_UIV)
                .setHasCorrespondingPlasma(true);

    public static Materials CherryBlossomDreamMatter = new Materials(
        offsetID + 4,
        TextureSet.SET_FLUID,
        1.0F,
        0,
        2,
        1|2|16 | 32 | 64 | 128 ,
        255,
        183,
        197,
        2,
        "CherryBlossomDreamMatter",
        "CherryBlossomDreamMatter",
        1,
        114514,
        1,
        0,
        false,
        false,
        2,
        1,
        1,
        Dyes._NULL,
        Arrays.asList(
            new TCAspects.TC_AspectStack(TCAspects.RADIO, 5),
            new TCAspects.TC_AspectStack(TCAspects.ALIENIS, 3))).disableAutoGeneratedBlastFurnaceRecipes()
                .disableAutoGeneratedVacuumFreezerRecipe()
                .setProcessingMaterialTierEU(TierEU.RECIPE_LuV)
                .setHasCorrespondingPlasma(true);

    // register Extra Information
    static {
        nanite.mGeneratedItems.add(MaterialCherryBlossom.Stygian);
        nanite.mGeneratedItems.add(MaterialCherryBlossom.Demise);
        nanite.mGeneratedItems.add(MaterialCherryBlossom.CherryBlossomDreamMatter);

        Demise.mChemicalFormula = "¤De\u2087✪Mi❦Se\u2082҉?";
        Stygian.mChemicalFormula = "۞\u2085(Sty⚶)\u2083⸎\u2082Gian*＊✲" + CharExchanger.shifter(9191);
        CherryBlossomDreamMatter.mChemicalFormula = "¤\u2087❀❀❀\u2082҉?";

        SubTag.METAL.addTo(Demise, Stygian, CherryBlossomDreamMatter);
    }

    public static void initClient() {
        if (Avaritia.isModLoaded()) {
            try {
                Demise.renderer = new InfinityStygianTranscendentMetalRenderer();
                Stygian.renderer = new InfinityStygianRenderer();
                CherryBlossomDreamMatter.renderer = new GeneratedMaterialRenderer();
                LOG.info("Successfully initialized custom renderers for Demise and Stygian materials");
            } catch (Exception e) {
                LOG.error("Failed to initialize custom renderers", e);
                // 使用默认渲染器作为后备
                Demise.renderer = new GeneratedMaterialRenderer();
                Stygian.renderer = new GeneratedMaterialRenderer();
            }
        } else {
            LOG.warn("Avaritia mod not found, using default renderers");
            Demise.renderer = new GeneratedMaterialRenderer();
            Stygian.renderer = new GeneratedMaterialRenderer();
        }
    }

    public static void init() {
        // Initialize materials
    }
}
